version: "3.8"

services:
  backend:
    build: ./Api
    container_name: prestamos-backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: loan
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: prestamos-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: loan
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build: ./Frontend
    container_name: prestamos-frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USERPOLLING=true
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data:
