version: "3.8"

services:
  backend:
    build: ./Api
    container_name: prestamos-backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: prestamos
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: prestamos-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prestamos
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
